In [15]:
from euroleague_api.game_stats import GameStats
from euroleague_api.player_stats import PlayerStats
from euroleague_api.play_by_play_data import PlayByPlay

In [40]:
# En busca de si teniamos la información al respecto de las subsituticiones (y sus tiempos): SÍ.
# El único problema es que solo tenemos este dato desde 2007 (inclusive).

plays = PlayByPlay()

x = plays.get_game_play_by_play_data(season=2024, gamecode=17)

x[(x['PLAYINFO']=='In') | (x['PLAYINFO']=='Out')]

,Season,Gamecode,TYPE,NUMBEROFPLAY,CODETEAM,PLAYER_ID,PLAYTYPE,PLAYER,TEAM,DORSAL,MINUTE,MARKERTIME,POINTS_A,POINTS_B,COMMENT,PLAYINFO,PERIOD
38,2024,17,0,81,BAR,P002939,IN,"SATORANSKY, TOMAS",FC Barcelona,13,5,05:32,NaN,NaN,,In,1
39,2024,17,0,82,BAR,P010106,OUT,"NUNEZ, JUAN",FC Barcelona,17,5,05:32,NaN,NaN,,Out,1
42,2024,17,0,86,BER,P011934,OUT,"WETZELL, YANNI",ALBA Berlin,5,6,04:58,NaN,NaN,,Out,1
43,2024,17,0,87,BER,P010791,IN,"KOUMADJE, KHALIFA",ALBA Berlin,21,6,04:58,NaN,NaN,,In,1
44,2024,17,0,88,BER,P011631,IN,"RAPIEQUE, ELIAS",ALBA Berlin,25,6,04:58,NaN,NaN,,In,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,2024,17,0,578,BAR,P006435,IN,"LAPROVITTOLA, NICOLAS",FC Barcelona,20,37,03:07,NaN,NaN,,In,4
513,2024,17,0,596,BER,P011934,IN,"WETZELL, YANNI",ALBA Berlin,5,39,01:17,NaN,NaN,,In,4
514,2024,17,0,597,BER,P010791,OUT,"KOUMADJE, KHALIFA",ALBA Berlin,21,39,01:17,NaN,NaN,,Out,4
515,2024,17,0,599,BER,P006919,OUT,"OLINDE, LOUIS",ALBA Berlin,19,39,01:17,NaN,NaN,,Out,4
516,2024,17,0,600,BER,P012721,IN,"BEAN, JUSTIN",ALBA Berlin,34,39,01:17,NaN,NaN,,In,4